# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "root": "test_nbdev.ipynb",
    "read_item": "test_nbdev.ipynb",
    "main": "test_nbdev.ipynb",
    "app": "test_nbdev.ipynb",
}

modules = ["main.py"]

doc_url = "https://recsyslabs.github.io/myapi/"

git_url = "https://github.com/recsyslabs/myapi/tree/master/"


def custom_doc_links(name):
    return None
